version: "3"

services:
  qbittorrent:
    container_name: qbittorrent
    image: ${IMAGE:-llscr.io/linuxserver/qbittorrent}
    restart: unless-stopped
    mac_address: ${MAC}
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      WEBUI_PORT: 8080
    networks:
      lan:
        ipv4_address: ${IP}
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - data:/config
      - downloads:/downloads

networks:
  lan:
    external: true

volumes:
  data: {}
  downloads: {}
