version: "3"

services:
  minecraft:
    container_name: minecraft
    image: ${IMAGE:-itzg/minecraft-server}
    restart: unless-stopped
    mac_address: ${MAC}
    environment:
      EULA: true
      TYPE: FABRIC
      MODRINTH_PROJECTS: lithium,plasmo-voice
      MODRINTH_ALLOWED_VERSION_TYPE: release
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: false
      MEMORY: 1G
      ENABLE_RCON: false
      MOTD: ${MOTD}
      DIFFICULTY: hard
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: true
    networks:
      lan:
        ipv4_address: ${IP}
    ports:
      - 25565:25565
    volumes:
      - data:/data

networks:
  lan:
    external: true

volumes:
  data: {}
