version: "3"

services:
  minecraft:
    container_name: minecraft
    image: ${IMAGE:-itzg/minecraft-server}
    restart: unless-stopped
    environment:
      EULA: true
      TYPE: FABRIC
      MODRINTH_PROJECTS: lithium,starlight
      MODRINTH_ALLOWED_VERSION_TYPE: release
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: false
      MEMORY: 1G
      RCON_PASSWORD: $RCON_PASSWORD
      MOTD: $MOTD
      DIFFICULTY: hard
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      WHITELIST: $WHITELIST
      OPS: $OPS
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: true
    ports:
      - 25565:25565
    volumes:
      - data:/data

volumes:
  data: {}